### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by onetrev** [timneutkens/gulp-sass-error#1]
Call me crazy, but following the instructions for "Using require", this didn't work for me:
`.on('error', gulpSassError(throwError))`

I received _gulpSassError_ is not defined errors doing that. I'm guessing because we declare the constant to be `sassError` so you need to use that instead. As such, maybe what the readme needs to be updated to this instead?

 `.on('error', sassError(throwError))`

Or I could be totally wrong! But that worked for me at least. :)

**Comment by MaryBartlett** [comment]
I was just about to raise this exact same thing :+1:

**Comment by timneutkens** [comment]
True, Will update in a sec. Thanks for the issue 👍🏻

**Comment by timneutkens** [comment]
Fixed.
