### ISSUE TITLE
1.0.3 NPM module doesn't include code

### ISSUE THREAD

**Issue by christarczon** [timneutkens/gulp-sass-error#2]
It looks like 1.0.3 wasn't deployed to NPM correctly. There's no dist folder. Which is kind of important! :)

**Comment by DCstewieG** [comment]
Not sure what you mean. I reverted to 1.0.2 which is fine.

**Comment by timneutkens** [comment]
Hmmm interesting. This is What you get for releasing an update on a package you don't use. I'll release a new update in 15mins. 👍🏻

**Comment by timneutkens** [comment]
Sorry for this.

**Comment by timneutkens** [comment]
Updated, added `prepublish` to always publish builded files in the future.
